spring:
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: glassofwaterlogin@gmail.com
    password: elecgjffafkgyaoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true