spring:
  jpa:
    generate-ddl: true
#  datasource:
#    url: jdbc:postgresql://localhost/bblex
#    username: bblex
#    password: bblex
#    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: glassofwaterlogin@gmail.com
    password: elecgjffafkgyaoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true