spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/bblex
    username: bblex
    password: bblex
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: player02145@gmail.com
    password: ahpujxcpiehoarej
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true